name: babiconsultancy
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  intl: ^0.18.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  smooth_page_indicator: ^1.1.0
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.7.0
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  unicons: ^2.1.1
  flutter_bloc: ^8.1.4
  webview_flutter: ^4.7.0
  flutter_easyloading: ^3.0.5
  firebase_core: ^2.31.0
  shared_preferences: ^2.2.2
  internet_connection_checker: ^1.0.0+1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  get_it: ^7.6.7
  random_avatar: ^0.0.8
  retrofit: '^4.1.0'
  logger: '^2.2.0'
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.8
  retrofit_generator: '^8.1.0'
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/vectors/
    - assets/images/jpeg/
    - assets/animation/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
